name: Staging Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_WORKING_DIR: ./infra
  RESOURCE_GROUP: sk-hd
  AKS_NAME: skhd-aks
  LOCATION: australiaeast
  ACR_NAME: skhdaks
  IMAGE_TAG: ${{ github.sha }}

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Import Existing Resources & Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_resource_group: ${{ env.RESOURCE_GROUP }}
          TF_VAR_aks_name: ${{ env.AKS_NAME }}
          TF_VAR_acr_name: ${{ env.ACR_NAME }}
          TF_VAR_location: ${{ env.LOCATION }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        run: |
          terraform import azurerm_resource_group.rg \
            /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }} || true
          terraform import azurerm_container_registry.acr \
            /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.ContainerRegistry/registries/${{ env.ACR_NAME }} || true
          terraform import azurerm_kubernetes_cluster.aks \
            /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.ContainerService/managedClusters/${{ env.AKS_NAME }} || true
          terraform apply -auto-approve

  docker_build_push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build & Push Product Service
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/product-service:${{ env.IMAGE_TAG }} ./backend/product_service
          docker push ${{ env.ACR_NAME }}.azurecr.io/product-service:${{ env.IMAGE_TAG }}

      - name: Build & Push Order Service
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/order-service:${{ env.IMAGE_TAG }} ./backend/order_service
          docker push ${{ env.ACR_NAME }}.azurecr.io/order-service:${{ env.IMAGE_TAG }}

  deploy_services:
    name: Deploy Backend Services to AKS
    runs-on: ubuntu-latest
    needs: docker_build_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_NAME }}

      - name: Deploy backend infrastructure & services
        run: |
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml
          kubectl apply -f product-service.yaml
          kubectl apply -f order-service.yaml

      - name: Update container images
        run: |
          kubectl set image deployment/product-service \
            product-service-container=${{ env.ACR_NAME }}.azurecr.io/product-service:${{ env.IMAGE_TAG }}
          kubectl set image deployment/order-service \
            order-service-container=${{ env.ACR_NAME }}.azurecr.io/order-service:${{ env.IMAGE_TAG }}

      - name: Wait for deployments to complete
        run: |
              function check_health() {
               local svc=$1
               local ip
               ip=$(kubectl get svc $svc -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
               echo "🔗 $svc IP: $ip"
          
               for i in {1..12}; do
                echo "Checking $svc health attempt $i..."
                if curl -f --max-time 5 http://$ip:8080/api/health; then
                   echo "✅ $svc is healthy"
                  return 0
                fi
                 sleep 5
               done
          
              echo "❌ $svc health check failed after retries!"
              echo "📝 Pod logs for $svc:"
              kubectl logs -l app=$svc --tail=50
              exit 1
        }

        for dep in product-service order-service; do
          echo "⏳ Waiting for $dep rollout..."
          kubectl rollout status deployment/$dep --timeout=300s || (kubectl get pods -o wide; exit 1)
          check_health $dep
        done

        echo "🎉 All deployments verified successfully!"


  
  terraform_destroy:
    name: Destroy Staging Resources
    runs-on: ubuntu-latest
    needs: deploy_services
    if: always()  # ensures cleanup even if previous steps fail
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      -  name: Terraform Init
         working-directory: ${{ env.TF_WORKING_DIR }}
         run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_resource_group: ${{ env.RESOURCE_GROUP }}
          TF_VAR_aks_name: ${{ env.AKS_NAME }}
          TF_VAR_location: ${{ env.LOCATION }}
        run: terraform destroy -auto-approve
